spring.application.name=user-service

# Load MongoDB URI from Environment Variable
spring.data.mongodb.uri=mongodb+srv://admin2:admin2@cluster0.tolrc.mongodb.net/CSTMs-Users

server.port=8082

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/